### ISSUE TITLE
Unable to retrieve JWTs with a Consumer that only has a custom_id

### ISSUE THREAD

**Issue by sleepingstu** [kontena/kong-client-ruby#17]
If I create a Kong consumer using only a `custom_id` (so have no `username`) I'm unable to retrieve  that consumers JWTs using `Kong::Consumer.find_by_custom_id("foo").jwts`.

I did some digging and in `lib/kong/consumer.rb` line 94, the client call to get the JWTs is using`client.get("#{@api_end_point}#{self.username}/jwt")` but because username is nil nothing is returned.

Should (or could) this be more like `client.get("#{@api_end_point}#{self.username || self.custom_id}/jwt")`?

**Comment by nevalla** [comment]
Thanks for reporting this. According to [Kong documentation](https://getkong.org/docs/0.11.x/admin-api/#retrieve-consumer) consumer can be retrieved by username or id, so I think it's safe to use `self.id`:
```ruby
client.get("#{@api_end_point}#{self.id}/jwt"
```
