### ISSUE TITLE
Cannot delete a consumer without a custom_id

### ISSUE THREAD

**Issue by Tuxii** [kontena/kong-client-ruby#5]
Hello,

I tried to call the `delete` method on a consumer object but it crashed : 
`Kong::Error: {"message":"An unexpected error occurred"}`

The SQL log of my kong server displays : 

```
db_1      | ERROR:  operator does not exist: text = boolean at character 270
db_1      | HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
db_1      | STATEMENT:  SELECT COUNT(*) FROM oauth2_tokens LEFT OUTER JOIN ttls ON (oauth2_tokens.id = ttls.primary_uuid_value) WHERE
db_1      | 	    (ttls.primary_key_value IS NULL OR (ttls.table_name = 'oauth2_tokens' AND expire_at > CURRENT_TIMESTAMP(0) at time zone 'utc')) AND "authenticated_userid" = TRUE
```
After some investigation, I found what caused the issue : https://github.com/kontena/kong-client-ruby/blob/master/lib/kong/consumer.rb#L68

Since the consumer object I'm working on, does not have a custom_id attribute set, this method send `{authenticated_userid:nil }` as params which will then be encoded as `"authenticated_userid"` and then seems to be evaluted to TRUE in PostgreSQL.

I don't know what would be the best way to solve this issue :

- Edit the `Kong::Client#encode_params` method to return `"param_name=null"` in case of nil values. 
- Not sending the `authenticated_userid` param if custom_id is nil in `Kong::Consumer#oauth_tokens` method

What do you think ? 

Thank you for your work on this gem by the way :)

**Comment by nevalla** [comment]
I ended up just to add check that if `custom_id` is nil, then oauth tokens are not fetched at all for consumer.
